name: Cloudflare Worker Deploy

on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.11.0
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run deploy
